const data = [
    {
        date: 'Понедельник',
        schedules: [
            {
				id:1,
                time: '12:00 13:15',
                name: 'Power lifting schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Grand Pool',
                trainer: 'Салаев Рустам',
                date: 'Понедельник',
            },
            {
				id:2,
                time: '14:00 15:15',
                name: 'Yoga schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Yoga Studio',
                trainer: 'Иванова Екатерина',
                date: 'Понедельник',
            },
            {
				id:3,
                time: '16:00 17:15',
                name: 'Zumba schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Dance Hall',
                trainer: 'Петрова Анна',
                date: 'Понедельник',
            },
        ],
    },
    {
        date: 'Вторник',
        schedules: [
            {
				id:4,
                time: '10:00 11:15',
                name: 'Pilates schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Pilates Studio',
                trainer: 'Козлова Ольга',
            },
            {
				id:5,
                time: '12:30 13:45',
                name: 'CrossFit schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, CrossFit Arena',
                trainer: 'Михайлов Иван',
            },
            {
				id:6,
                time: '16:30 17:45',
                name: 'Swimming schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Swimming Pool',
                trainer: 'Сидорова Александра',
            },
        ],
    },
    {
        date: 'Среда',
        schedules: [
			{
				id:7,
                time: '10:00 11:15',
                name: 'Pilates schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Pilates Studio',
                trainer: 'Козлова Ольга',
            },
            {
				id:7,
                time: '12:30 13:45',
                name: 'CrossFit schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, CrossFit Arena',
                trainer: 'Михайлов Иван',
            },
            {
				id:8,
                time: '16:30 17:45',
                name: 'Swimming schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Swimming Pool',
                trainer: 'Сидорова Александра',
            },
        ],
    },
    {
        date: 'Четверг',
        schedules: [
			{
				id:9,
                time: '10:00 11:15',
                name: 'Pilates schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Pilates Studio',
                trainer: 'Козлова Ольга',
            },
            {
				id:10,
                time: '12:30 13:45',
                name: 'CrossFit schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, CrossFit Arena',
                trainer: 'Михайлов Иван',
            },
            {
				id:11,
                time: '16:30 17:45',
                name: 'Swimming schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Swimming Pool',
                trainer: 'Сидорова Александра',
            },
        ],
    },
    {
        date: 'Пятница',
        schedules: [
            {
				id:12,
                time: '10:00 11:15',
                name: 'Pilates schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Pilates Studio',
                trainer: 'Козлова Ольга',
            },
            {
				id:13,
                time: '12:30 13:45',
                name: 'CrossFit schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, CrossFit Arena',
                trainer: 'Михайлов Иван',
            },
            {
				id:14,
                time: '16:30 17:45',
                name: 'Swimming schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Swimming Pool',
                trainer: 'Сидорова Александра',
            },
        ],
    },
    {
        date: 'Суббота',
        schedules: [
            {
				id:15,
                time: '10:00 11:15',
                name: 'Pilates schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Pilates Studio',
                trainer: 'Козлова Ольга',
            },
            {
				id:16,
                time: '12:30 13:45',
                name: 'CrossFit schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, CrossFit Arena',
                trainer: 'Михайлов Иван',
            },
            {
				id:17,
                time: '16:30 17:45',
                name: 'Swimming schedule',
                corpus: 'Главный учебный корпус',
                place: 'Жандосова 55/2, Swimming Pool',
                trainer: 'Сидорова Александра',
            },
        ],
    },
]

export default data
